language: csharp
mono: none
dotnet: 2.1
script:
   -  dotnet build BasicExample/BasicExample/BasicExample.csproj
   -  dotnet build EntityFrameworkExample/EntityFrameworkExample/EntityFrameworkExample.csproj